# Generated by Django 4.2.3 on 2023-08-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_alter_match_match_number_finalclassification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalclassification",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.player"
            ),
        ),
    ]
