# Generated by Django 4.2.3 on 2023-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0003_alter_finalclassification_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pts_in_general",
            field=models.BooleanField(default=False),
        ),
    ]
